const sidebars = {
  homepageSidebar: [{type: 'autogenerated', dirName: '.'}],

  BoardsSidebar: [{type: 'autogenerated', dirName: 'Boards'}],

  BoardsSTM32Sidebar: [{type: 'autogenerated', dirName: 'Boards/STM32'}],
  BoardsSTM32DNN647Sidebar: [{type: 'autogenerated', dirName: 'Boards/STM32/DNN647'}],

  BoardsKendryteSidebar: [{type: 'autogenerated', dirName: 'Boards/Kendryte'}],
  BoardsKendryteDNK230DSidebar: [{type: 'autogenerated', dirName: 'Boards/Kendryte/DNK230D'}],

  BoardsMinimumSidebar: [{type: 'autogenerated', dirName: 'Boards/Minimum'}],
  BoardsMinimumDNRP2350AMSidebar: [{type: 'autogenerated', dirName: 'Boards/Minimum/DNRP2350AM'}],

  BoardsLinuxSidebar: [{type: 'autogenerated', dirName: 'Boards/Linux'}],
  BoardsLinuxIMX6USidebar: [{type: 'autogenerated', dirName: 'Boards/Linux/IMX6U'}],
  BoardsLinuxDL2K0300Sidebar: [{type: 'autogenerated', dirName: 'Boards/Linux/DL2K0300'}],
  BoardsLinuxDLIMX93Sidebar: [{type: 'autogenerated', dirName: 'Boards/Linux/DLIMX93'}],
  BoardsLinuxCLRK3568FSidebar: [{type: 'autogenerated', dirName: 'Boards/Linux/CLRK3568F'}],
  BoardsLinuxDLRK3588Sidebar: [{type: 'autogenerated', dirName: 'Boards/Linux/DLRK3588'}],
  BoardsLinuxSTM32MP157Sidebar: [{type: 'autogenerated', dirName: 'Boards/Linux/STM32MP157'}],
  BoardsLinuxDLMP135Sidebar: [{type: 'autogenerated', dirName: 'Boards/Linux/DLMP135'}],
  BoardsLinuxDLAM62xSidebar: [{type: 'autogenerated', dirName: 'Boards/Linux/DLAM62x'}],
  BoardsLinuxDLT113ISSidebar: [{type: 'autogenerated', dirName: 'Boards/Linux/DLT113IS'}],
  BoardsLinuxSTM32MP257Sidebar: [{type: 'autogenerated', dirName: 'Boards/Linux/STM32MP257'}],

  CardComputerSidebar: [{type: 'autogenerated', dirName: 'CardComputer'}],

  CardComputerAtomPiCA1Sidebar: [{type: 'autogenerated', dirName: 'CardComputer/AtomPi-CA1'}],
};

export default sidebars;
