const sidebars = {
  homepageSidebar: [{type: 'autogenerated', dirName: '.'}],
  DNK230DSidebar: [{type: 'autogenerated', dirName: 'Boards/Kendryte/DNK230D'}],
  IMX6USidebar: [{type: 'autogenerated', dirName: 'Boards/Linux/IMX6U'}],
};

export default sidebars;
